# Generated by Django 2.2.7 on 2020-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueweb', '0003_song_hosting'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='direct_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='hosting',
            field=models.CharField(blank=True, choices=[('soundcloud', 'SoundCloud'), ('bandcamp', 'BandCamp'), ('youtube', 'YouTube')], max_length=100),
        ),
    ]
