# Generated by Django 2.2.7 on 2020-11-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blueweb', '0005_release_hyperfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperfollowHotlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotlink', to='blueweb.Release')),
            ],
        ),
    ]
