# Generated by Django 2.2.7 on 2020-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueweb', '0006_hyperfollowhotlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperfollowhotlink',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
