# Generated by Django 2.2.7 on 2020-12-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueweb', '0007_hyperfollowhotlink_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover_art',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
